[package]
name = "typical90"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "=0.3.7", features = ["derive"] }
num-integer = "=0.1.42"
petgraph = "=0.5.0"

[profile.release]
lto = true
panic = 'abort'
