[package]
name = "abc185"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "=0.3.7", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
