[package]
name = "abc070"
version = "0.1.0"
authors = ["sugyan <sugi1982@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
num-integer = "=0.1.42"
proconio = { version = "=0.3.7", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
